name: Pull Request Manager

on:
  pull_request_target:

jobs:
  pr_manager:
    name: PR Manager
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true

      - uses: actions/checkout@v2
      - name: Clang-Format Lint Verify
        uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: '.'
          extensions: 'h,c,inl'
          clangFormatVersion: 10
